# Generated by Django 5.1.7 on 2025-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customsuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsuser',
            options={'permissions': [('can_block_user', 'Блокировка пользователя')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='customsuser',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='customsuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customsuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customsuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customsuser',
            name='phone',
            field=models.CharField(blank=True, help_text='введи номер телефона', max_length=35, null=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='customsuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photo/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customsuser',
            name='country',
            field=models.CharField(blank=True, help_text='Укажите страну', max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='customsuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customsuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customsuser',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Token'),
        ),
    ]
