# Generated by Django 5.2 on 2025-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),    # noqa
                ('date_first_message', models.DateTimeField(blank=True, help_text='укажите время в формате 2023-10-01 12:00', null=True)),    # noqa
                ('date_end_message', models.DateTimeField(blank=True, help_text='укажите время в формате 2023-10-01 12:00', null=True)),     # noqa
                ('status', models.CharField(blank=True, choices=[('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена'), ('blocked', 'Заблокирована'), ('unblocked', 'Разблокирована')], default='created', max_length=20, verbose_name='Статус')),   # noqa
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['date_first_message', 'message'],
                'permissions': [('can_view_other_mailing', 'Может просматривать чужие рассылки'), ('can_mailing_blocked', 'Может блокировать рассылки')],    # noqa
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),    # noqa
                ('date_time_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')),     # noqa
                ('mail_server_response', models.TextField(verbose_name='Ответ почтового сервера')),    # noqa
                ('status', models.CharField(blank=True, choices=[('successfully', 'Успешно'), ('not_successfully', 'Не успешно')], default='not_successfully', max_length=16, verbose_name='Статус')),    # noqa
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ['date_time_attempt'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),     # noqa
                ('theme_message', models.CharField(max_length=150, verbose_name='Тема письма')),    # noqa
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['theme_message'],
                'permissions': [('can_view_other_message', 'Может просматривать чужие сообщения')],    # noqa
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),    # noqa
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email получателя')),     # noqa
                ('full_name', models.CharField(unique=True, verbose_name='ФИО получателя')),      # noqa
                ('comment', models.TextField(blank=True, max_length=150, null=True, verbose_name='Комментарий')),   # noqa
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['full_name'],
                'permissions': [('can_view_other_client', 'Может просматривать чужих клиентов')],   # noqa
            },
        ),
    ]
