# Generated by Django 5.2 on 2025-04-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='mail_server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера'),    # noqa
        ),
    ]
