# Generated by Django 5.1.7 on 2025-04-09 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingattempt_mail_server_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='recipient',
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['first_sending'], 'permissions': [('set_is_active', 'set is active')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_blocking_sms', 'Может блокировать сообщение')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='date_end_message',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='date_first_message',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='theme_message',
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_sending',
            field=models.DateTimeField(blank=True, help_text='гггг-мм-дд чч:мм:сс', null=True, verbose_name='Дата окончания отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='first_sending',
            field=models.DateTimeField(blank=True, help_text='гггг-мм-дд чч:мм:сс', null=True, verbose_name='Дата первой отправки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='активна'),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое письма'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создано', 'Создано'), ('Запущено', 'Запущено'), ('Завершена', 'Завершена')], default='Создано', max_length=11, verbose_name='Статус рассылки'),
        ),
        migrations.CreateModel(
            name='AttemptMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], max_length=15, verbose_name='Статус попытки')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing', to='mailing.mailing', verbose_name='Рассылка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
                'ordering': ['date_attempt', 'status'],
            },
        ),
        migrations.CreateModel(
            name='ReceiveMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
                'ordering': ['fio'],
                'permissions': [('can_blocking_client', 'Может блокировать получателя')],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='mailing.receivemail', verbose_name='Клиент'),
        ),
        migrations.DeleteModel(
            name='MailingAttempt',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
